#ifndef MAIN_BOARD_H
#define MAIN_BOARD_H

#define POWER_STRIP_CONFIG_FILE_NAME "power_strip.conf"
#define POWER_STRIP_DEVICE_CONTROL_NAME_LENGTH 50
#define SETUP_DEVICE_COMMAND_BUF_LEN 100

#define MESSAGE_TO_BOARD_LENGTH 5
#define MAX_RELAY 9 //including device name at first line
#define MAX_RELAY_NAME_LENGTH 50

#define DEVICE_IDX 0
#define RELAY1_IDX 1
#define RELAY2_IDX 2
#define RELAY3_IDX 3
#define RELAY4_IDX 4
#define RELAY5_IDX 5
#define RELAY6_IDX 6
#define RELAY7_IDX 7
#define RELAY8_IDX 8

#define MIN_RELAY_IDX 0
#define MAX_RELAY_IDX 7

#define RELAY_ON 'O'
#define RELAY_OFF 'F'

#define RELAY_GET_STATUS 'G'

#define RELAY_SET_STATUS 'S'

#define RELAYS_MESSAGE_OPTION_INDEX 2
#define RELAYS_MESSAGE_RELAY_INDEX  3
#define RELAYS_MESSAGE_CRC_INDEX    4

#define RELAYS_MESSAGE_ALL_ON 0xff
#define RELAYS_MESSAGE_ALL_OFF 0x0

#endif  // MAIN_BOARD_H